# Generated by Django 4.2.23 on 2025-07-11 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_state_district"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="district",
            name="state",
        ),
        migrations.DeleteModel(
            name="user",
        ),
        migrations.DeleteModel(
            name="District",
        ),
        migrations.DeleteModel(
            name="State",
        ),
    ]
