# Generated by Django 4.2.23 on 2025-07-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_user_district_user_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_varified",
            field=models.BooleanField(default=False),
        ),
    ]
