# Generated by Django 4.2.23 on 2025-07-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_user_is_varified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=254),
        ),
    ]
