# Generated by Django 4.2.23 on 2025-07-16 05:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verification_token",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="reset_expire",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="reset_token",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
